# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonProject

  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher', '= 4.8.1'
  pod 'ObjectMapper', '= 3.3.0'
  pod 'RealmSwift'
  pod 'SVProgressHUD', '= 2.2.5'

end
